CREATE TABLE "LIBRARY"
(    
   "BOOK_ID" INT not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),   
   "BOOKNAME" VARCHAR(50),     
   "AUTHOR_FNAME" VARCHAR(50),
   "AUTHOR_LNAME" VARCHAR(50),
   "PUBLISHER" VARCHAR(50),
   "PRICE" DECIMAL(6,2) NOT NULL,  
   "CATEGORY" VARCHAR(50),
   "SUBCATEGORY" VARCHAR(100),
   "READED" BOOLEAN
);